### ISSUE TITLE
[Bug] bees get stuck entering/exiting doors and climbing ladders

### ISSUE THREAD

**Issue by ajsglist** [AudioKnight/Starlancer#32]
Hi there,

No logs to pass along because nothing was being thrown, but the bees have been observed getting stuck as described in the title.  Specifically, they are observed getting stuck in entrance/exit loops with doors (both main and side) in addition to getting stuck in ladder climbing loops (climbing up/down/up infinitely)

**Comment by AudioKnight** [comment]
Sorry, been a while since I checked here. Was this fixed by the most recent update? I removed the instantiated nodes at the doors. If this issue occurred on a custom moon, then it's likely because there's too few OutsideAINodes near the entrances.

Ladder loops I think are a vanilla bug.

**Comment by ajsglist** [comment]
The current version when I made this was 2.4.0.  I upgraded to 2.4.1 but haven't had much time to test anything, so I can't say anything about that version at the moment.

**Comment by MPRATCH-V2** [comment]
Using the most recent version on vanilla moons this still occurs. I do have an extensive modlist though so not sure if its caused by conflictions/general instability

**Comment by ajsglist** [comment]
closing this out since Bees were blacklisted in 2.4.2

Cheers
